#!/bin/sh
#----------------------------------------------------------
# RUN
#
# uses bridge as engine
#
# USAGE: run [bridge options .....]
#        run -h for help
#----------------------------------------------------------

echo "-----------------------"

/etc/init.d/phin_bridge stop

echo "-----------------------"

unlock

echo "-----------------------"

./bridge $@
