#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10

PIN="2"

error() {
  logger -t gpiosetup -p daemon.err "${1:-'Unknown error'}"
  exit 42
}

start() {
  echo "${PIN}" > /sys/class/gpio/export || error "export"
  PIN_DIR="/sys/class/gpio/gpio${PIN}" || error "PIN_DIR"
  echo "in" > ${PIN_DIR}/direction || error "direction"
  echo "1" > ${PIN_DIR}/active_low || error "active_low"

  logger -t gpiosetup -p daemon.notice "Successfully configured GPIO for pin ${PIN}"
}
