#!/bin/sh

uci -q batch <<-EOT
        set wireless.mt7628.country=US
        set wireless.mt7628.region=0
        set wireless.sta=wifi-iface
        set wireless.sta.device=mt7628
        set wireless.sta.network=wwan
        set wireless.sta.mode=sta
        set wireless.sta.ifname=apcli0
        delete wireless.@wifi-iface[0].mode
        delete wireless.@wifi-iface[0].ssid
        delete wireless.@wifi-iface[0].encryption
        delete wireless.@wifi-iface[0].key
EOT
