#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

BINFILE="/opt/phin/bridge"
FIRMWARE="/opt/phin/firmware"
ADMIN="/opt/phin/admin"
BINOPTS="-F"

UNLOCK="/opt/phin/unlock"

set_cron() {
  REBOOTED_FILE="/etc/phin-auto-rebooted.txt"
  if [[ ! -f "$REBOOTED_FILE" ]]; then
    echo "PREPARING CRON"
    RANDMIN=$(awk -v min=0 -v max=59 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')   # minute 0 to min 59
    RANDHR=$(awk -v min=7 -v max=9 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')     # approx CA 12am to 2am
    CRONTAB="${RANDMIN} ${RANDHR}"
    echo "SETTING CRON RESTART AS: $CRONTAB UTC"
    echo $CRONTAB '* * * sleep 70 && touch /etc/banner && date >' $REBOOTED_FILE '&& reboot' > /etc/crontabs/root
  fi
}

disable_ap() {
  uci set wireless.@wifi-iface[0].disabled='1'
  uci commit wireless
  wifi
}

start_service() {
  set_cron
  #disable_ap ## This does not seem to be late enough! ARGH!
  procd_open_instance phin_bridge
  procd_set_param command ${BINFILE} ${BINOPTS} -i ${FIRMWARE} -a ${ADMIN}

  # respawn automatically if something died, be careful if you have an alternative process supervisor
  procd_set_param respawn 3600 5 0

  # procd_set_param env SOME_VARIABLE=funtimes  # pass environment variables to your process
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_close_instance
}

stop_service() {
  echo "Stopping bridge"
  ${UNLOCK}
}
