#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

BINFILE=/opt/phin/bridge
PIDFILE=/var/bridge.pid

start_service() {
  procd_open_instance
  procd_set_param command ${BINFILE}
  echo "Starting phin_bridge. pidfile is ${PIDFILE}"
  # logger -t "Starting phin_bridge. pidfile is ${PIDFILE}"
  # respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

  # procd_set_param env SOME_VARIABLE=funtimes  # pass environment variables to your process
  # procd_set_param limits core="unlimited"  # If you need to set ulimit for your process
  # procd_set_param file /var/etc/your_service.conf # /etc/init.d/your_service reload will restart the daemon if these files have changed
  # procd_set_param netdev dev # likewise, except if dev's ifindex changes.
  # procd_set_param data name=value ... # likewise, except if this data changes.
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  # procd_set_param user nobody # run service as user nobody
  procd_set_param pidfile ${PIDFILE} # write a pid file on instance start and remote it on stop
  procd_close_instance
}
