#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /opt/Playground/bin/playgroundble
        procd_set_param respawn ${respawn_retry:-0}
        procd_close_instance

	procd_open_instance
        procd_set_param command /bin/node /opt/ConnectedYard/ConnectedYardMain.js
        procd_set_param respawn ${respawn_retry:-0}
        procd_close_instance	
}

